### ISSUE TITLE
./instainsane.sh: line 573: [: too many arguments

### ISSUE THREAD

**Issue by blunts1498** [thelinuxchoice/instainsane#2]
Getting this message after it running for a while, then it stops running

Trying pass (47979/14344391): "staci"
Trying pass (47980/**3562105**): "14344391"
Trying pass (st.louis/): ""
./instainsane.sh: line 573: [: too many arguments

**Comment by thelinuxchoice** [comment]
its a problem with your wordlist. 
try this:
cat yourwordlist.txt | uniq > newwordlist

**Comment by wtfmark** [comment]
> its a problem with your wordlist.
> try this:
> cat yourwordlist.txt | uniq > newwordlist

I have tried this and still get the error. Also confirmed I dont have anything weird like spaces or blank lines etc and error persists

**Comment by dig-sisyphos** [comment]
> its a problem with your wordlist.
> try this:
> cat yourwordlist.txt | uniq > newwordlist

thank you sir

**Comment by analjesus** [comment]
This is not a problem with the wordlist. That is an ignorant assessment. The problem is with grep. You need to escape special characters in grep by using the fgrep. Go through the script and replace all instances of `countpass=$(grep -n -x "$pass" "$wl_pass" | cut -d ":" -f1)` with `countpass=$(grep -F -n -x "$pass" "$wl_pass" | cut -d ":" -f1)`

**Comment by 5po0k** [comment]
> This is not a problem with the wordlist. That is an ignorant assessment. The problem is with grep. You need to escape special characters in grep by using the fgrep. Go through the script and replace all instances of `countpass=$(grep -n -x "$pass" "$wl_pass" | cut -d ":" -f1)` with `countpass=$(grep -F -n -x "$pass" "$wl_pass" | cut -d ":" -f1)`

Thanks this worked perfect.

**Comment by bondzync** [comment]
> 
> 
> > This is not a problem with the wordlist. That is an ignorant assessment. The problem is with grep. You need to escape special characters in grep by using the fgrep. Go through the script and replace all instances of `countpass=$(grep -n -x "$pass" "$wl_pass" | cut -d ":" -f1)` with `countpass=$(grep -F -n -x "$pass" "$wl_pass" | cut -d ":" -f1)`
> 
> Thanks this worked perfect.

Hello
I am using Kali Linux on windows 10.
and i am getting this error. Can you tell me how to use grep and fix it.
Thank You
