### ISSUE TITLE
For isn't installed

### ISSUE THREAD

**Issue by k13rancat** [thelinuxchoice/instainsane#3]
Hi I have instainsane setup but below it says I require for buy it isn't installed run./install.sh...now when I do that it says for not installed all requires are installed please help

**Comment by thelinuxchoice** [comment]
check your sources.list or dpkg/apt issues

**Comment by root-420** [comment]
Your sources.list should look like this to install tor.
deb http://http.kali.org/kali kali-rolling main non-free contrib


Do so by
$ sudo gedit /etc/apt/sources.list 
and modify with the text above. Hope it work for you as well as it did for me :) Happy Hacking \m/
