### ISSUE TITLE
Tor connection

### ISSUE THREAD

**Issue by shuhrat02** [thelinuxchoice/instainsane#4]
Hi! tnx for instainsane!

I have a questuion: Do i need to run TOR mannualy? or ur soft will do it automatically? 

due to I have an error during connection:

Password List (Enter to default list): 
[*] Starting Tor on port: 9051
[*] Starting Tor on port: 9052
[*] Starting Tor on port: 9053
[*] Starting Tor on port: 9054
[*] Starting Tor on port: 9055
[*] Checking Tor connection on port: 9051...FAIL!
[*] Checking Tor connection on port: 9052...OK!
[*] Checking Tor connection on port: 9053...OK!
[*] Checking Tor connection on port: 9054...OK!
[*] Checking Tor connection on port: 9055...OK!
Require all TOR connection running to continue. Exiting

upd: in both metods of conenction, instainsane, says that port 9051...Failed.

sos, pls help?

**Comment by shuhrat02** [comment]
`netstat -ntulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      821/python3         
tcp        0      0 127.0.0.1:9040          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9051          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9052          0.0.0.0:*               LISTEN      30076/tor           
tcp        0      0 127.0.0.1:9053          0.0.0.0:*               LISTEN      30108/tor           
tcp        0      0 127.0.0.1:9054          0.0.0.0:*               LISTEN      30140/tor           
tcp        0      0 127.0.0.1:9055          0.0.0.0:*               LISTEN      30172/tor           
udp        0      0 127.0.0.1:53            0.0.0.0:*                           613/tor             
udp        0      0 0.0.0.0:68              0.0.0.0:*                           31834/dhclient      
udp        0      0 0.0.0.0:47291           0.0.0.0:*                           2647/openvpn`

**Comment by shuhrat02** [comment]
``

> netstat -ntulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      821/python3         
tcp        0      0 127.0.0.1:9040          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9051          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9052          0.0.0.0:*               LISTEN      30076/tor           
tcp        0      0 127.0.0.1:9053          0.0.0.0:*               LISTEN      30108/tor           
tcp        0      0 127.0.0.1:9054          0.0.0.0:*               LISTEN      30140/tor           
tcp        0      0 127.0.0.1:9055          0.0.0.0:*               LISTEN      30172/tor           
udp        0      0 127.0.0.1:53            0.0.0.0:*                           613/tor             
udp        0      0 0.0.0.0:68              0.0.0.0:*                           31834/dhclient      
udp        0      0 0.0.0.0:47291           0.0.0.0:*                           2647/openvpn

**Comment by shuhrat02** [comment]
Here  netstat of PC:

`#netstat -ntulp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      821/python3         
tcp        0      0 127.0.0.1:9040          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9051          0.0.0.0:*               LISTEN      613/tor             
tcp        0      0 127.0.0.1:9052          0.0.0.0:*               LISTEN      30076/tor           
tcp        0      0 127.0.0.1:9053          0.0.0.0:*               LISTEN      30108/tor           
tcp        0      0 127.0.0.1:9054          0.0.0.0:*               LISTEN      30140/tor           
tcp        0      0 127.0.0.1:9055          0.0.0.0:*               LISTEN      30172/tor           
udp        0      0 127.0.0.1:53            0.0.0.0:*                           613/tor             
udp        0      0 0.0.0.0:68              0.0.0.0:*                           31834/dhclient      
udp        0      0 0.0.0.0:47291           0.0.0.0:*                           2647/openvpn`


PIDs for programms are different

**Comment by shuhrat02** [comment]
Pls, close this topic. Was fixed by killing TOR's pid

**Comment by raghavraagu** [comment]
[] Checking Tor connection on port: 9051...FAIL!

same error is getting pls help  i need the solution for this how can i solve this issue???

**Comment by ArminAkhlagh** [comment]
> [] Checking Tor connection on port: 9051...FAIL!
> 
> same error is getting pls help i need the solution for this how can i solve this issue???

`sudo killall tor`

**Comment by thisiselnino** [comment]
i did killall tor but doesnt work some of my ports failed but some are okay if you can please help me thanks

**Comment by ArminAkhlagh** [comment]
Hi,
What kind of messengers do you have?
Answer me to chat there.
ID: @ArminAkhlagh

در تاریخ سه‌شنبه ۱۰ مارس ۲۰۲۰،‏ ۲۲:۳۷ elnino <notifications@github.com>
نوشت:

**Comment by sudoscriptkid** [comment]
Hi

[] Starting Tor on port: 9051
[] Starting Tor on port: 9052
[] Starting Tor on port: 9053
[] Starting Tor on port: 9054
[] Starting Tor on port: 9055
[] Checking Tor connection on port: 9051...FAIL!
[] Checking Tor connection on port: 9052...OK!
[] Checking Tor connection on port: 9053...OK!
[] Checking Tor connection on port: 9054...OK!
[] Checking Tor connection on port: 9055...OK!

 I have the same issue please help
"the port 9051 FAIL! "


please tell how to fix it😒


thank you

**Comment by ArminAkhlagh** [comment]
i don't know
checkout this link from StackOverFlow maybe it will work
https://stackoverflow.com/questions/35699833/stem-is-giving-the-unable-to-connect-to-port-9051-error

**Comment by ArminAkhlagh** [comment]
> 
> 
> Hi
> 
> [] Starting Tor on port: 9051
> [] Starting Tor on port: 9052
> [] Starting Tor on port: 9053
> [] Starting Tor on port: 9054
> [] Starting Tor on port: 9055
> [] Checking Tor connection on port: 9051...FAIL!
> [] Checking Tor connection on port: 9052...OK!
> [] Checking Tor connection on port: 9053...OK!
> [] Checking Tor connection on port: 9054...OK!
> [] Checking Tor connection on port: 9055...OK!
> 
> I have the same issue please help
> "the port 9051 FAIL! "
> 
> please tell how to fix it😒
> 
> thank you

i don't know
checkout this link from StackOverFlow maybe it will work
https://stackoverflow.com/questions/35699833/stem-is-giving-the-unable-to-connect-to-port-9051-error
