### ISSUE TITLE
I require tor but it's not installed. Run ./install.sh. Aborting.

### ISSUE THREAD

**Issue by root-420** [thelinuxchoice/instainsane#5]
ERROR: I require tor but it's not installed. Run ./install.sh. Aborting.

I have TOR installed in my Linux and its even working well. :) Please Hep! as I want to test your script by my own and learn more about the world! 
Thanks.
![ss](https://user-images.githubusercontent.com/36526237/40773299-05a00734-64b2-11e8-89f6-947d5d251d77.png)

**Comment by C3DR1C0** [comment]
I have the same mistake, could you fix it?

**Comment by viperinedig88Z** [comment]
You fix this problem ?

**Comment by stackerofwheat** [comment]
How exactly does this script get around the fact that Instagram accounts
are locked out after something like 20 failed login attempts regardless if
they come from different IP addresses?? I’d be concerned about this before
worrying other bugs.

**Comment by pankaj2k19** [comment]
> I have the same mistake, could you fix it?

**Comment by mubzi** [comment]
guys try to setup tor problems like installing  the proxychains..... i had the same situation and this was helpful

**Comment by AushazumdFX** [comment]
PLease Guys How Can I fix THis "I require tor but it's not installed. Run ./install.sh. Aborting."

and you above guy can you please specipy how you excatly fix the issue by that installation you?
please help.

**Comment by Tchadimir** [comment]
apt-get install tor

**Comment by gitmnj** [comment]
@Tchadimir it is not working with me can you please help me please
and please share your preferable contact info

**Comment by Tchadimir** [comment]
https://www.youtube.com/watch?v=QfUTlkh0ugs
